services:
  agiloft:
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - ./logs:/usr/local/Agiloft/logs
    expose:
      - 80/tcp
    ports:
      - 80:80/tcp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALLER_URL=https://download.agiloft.com/binary/Agiloft-Release_28-28792-linux-64bit-setup.sh
        - INSTALLER_MD5=002efd82e52f0c9c33b9b4cdc7b91004
    image: agiloft/agiloft:28.28792
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 131971
        hard: 131971

  tunnel:
    image: cloudflare/cloudflared:latest
    pull_policy: always
    restart: unless-stopped
    expose:
      - 43337/tcp
    environment:
      - TUNNEL_URL=http://agiloft:80
      - TUNNEL_METRICS=0.0.0.0:43337
    command: tunnel --no-autoupdate
    depends_on:
      - agiloft
